library(tidyverse)
stats <- read_csv(file.choose())
head(stats)
mean(stats$Payroll)
mean(stats$Wins)
fit = lm(Wins ~ Payroll, data = stats)
summary(fit)
coefs <- coef(fit)
coefs
plot(stats$Payroll, stats$Wins, pch=20, col= 'red')
abline(coefs[1], coefs[2])
qt(.975, 29)
pt(1.94, 29)
math <- read_csv(file.choose())
head(math)
fit = lm(math ~ science, data = math)
summary(fit)
qt(.995,200-2)
dim(math)
confint(fit, level = 0.99)
cor.test(Wins ~ Payroll, data = stats)